# Generated by Django 4.2.3 on 2023-07-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="student's name only", max_length=150, verbose_name='student name')),
                ('tutor', models.CharField(help_text="tutor's name only", max_length=150, verbose_name='tutor name')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
