# Generated by Django 4.2.3 on 2023-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onlines', '0001_initial'),
        ('offlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offline',
            name='subject',
            field=models.ManyToManyField(to='onlines.subject'),
        ),
    ]
