# Generated by Django 4.2.3 on 2023-07-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offlines', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offline',
            options={'verbose_name_plural': 'offline_classes'},
        ),
    ]
