# Generated by Django 4.2.3 on 2023-07-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('offlines', '0001_initial'),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='offline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='offlines.offline'),
        ),
        migrations.AddField(
            model_name='photo',
            name='Offline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='offlines.offline'),
        ),
        migrations.AddField(
            model_name='photo',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='challenges.challenge'),
        ),
    ]
