# Generated by Django 4.2.3 on 2023-07-28 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_alter_class_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='class name only', max_length=150, verbose_name='class name')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('LVEC', 'LVEC'), ('UEEC', 'UEEC'), ('EDEC', 'EDEC')], max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('subjects', models.ManyToManyField(to='classes.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
