# Generated by Django 4.2.3 on 2023-07-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='subject',
            field=models.ManyToManyField(to='classes.subject'),
        ),
    ]
