# Generated by Django 4.2.3 on 2023-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('onlineClasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='subject',
            field=models.ManyToManyField(to='onlineClasses.subject'),
        ),
    ]
