# Generated by Django 4.2.3 on 2023-07-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_initial'),
        ('onlineClasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='onlineclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='onlineClasses.onlineclass'),
        ),
    ]
