# Generated by Django 4.0.10 on 2023-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMIDATE', 'INTERMIDATE'), ('ADVANCE', 'ADVANCE')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
